name: Tests
on:
  workflow_call:

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: numary
          POSTGRES_PASSWORD: numary
          POSTGRES_DB: numary
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install task
        uses: arduino/setup-task@v1
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Run tests
        run: task tests
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)