name: Tests
on:
  workflow_call:
    inputs:
      go_version:
        required: false
        type: string
        default: 1.18

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@v1
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go_version }}
          cache: true
      - run: go mod download
      - name: run tests
        run: task tests
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
