name: GoReleaser Release
on:
  workflow_call:
    secrets:
      NUMARY_GITHUB_TOKEN:
        required: true
      FURY_TOKEN:
        required: true

jobs:
  build:
    name: GoReleaser Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true
      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN   }}
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --parallelism 4 --rm-dist --skip-validate
