name: Launch Infracost on Staging

on:
  workflow_call:
    secrets:
      TERRAFORM_CLOUD_TOKEN:
        required: true
      INFRACOST_API_KEY:
        required: true

jobs:
  infracost:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    env:
      working-directory: .cloud/ressources
      TF_WORKSPACE: "staging"
    name: Run Infracost
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false # This is recommended so the `terraform show` command outputs valid JSON
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::955332203423:role/github-access
          role-duration-seconds: 3600
      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.working-directory }}
      - name: Terraform plan
        run: terraform plan -var-file ./tfvars/terraform.staging.tfvars -out tfplan.binary
        working-directory: ${{ env.working-directory }}
      - name: Terraform show
        run: terraform show -json tfplan.binary > plan.json
        working-directory: ${{ env.working-directory }}
      - name: Setup Infracost
        uses: infracost/actions/setup@v1
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Generate Infracost JSON
        run: infracost breakdown --path plan.json --format json --out-file /tmp/infracost.json
        working-directory: ${{ env.working-directory }}
      - name: Post Infracost comment
        uses: infracost/actions/comment@v1
        with:
          path: /tmp/infracost.json
          behavior: update # Create a single comment and update it. The "quietest" option.
